=== SmartITEngineering/smart-cms/content-api/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:cur="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
targetNamespace="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
>
		<xs:simpleType name="smartDate">
				<xs:restriction base="xs:dateTime">
						<xs:pattern value="[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]([+-][0-2][0-9]:[0-5][0-9])"/>
				</xs:restriction>
		</xs:simpleType>
		<xs:group name="contentTypeGrp">
				<xs:sequence>
						<xs:element name="typeNS" type="xs:string" />
						<xs:element name="typeName" type="xs:string" />
				</xs:sequence>
		</xs:group>
		<xs:complexType name="value">
				<xs:sequence>
						<xs:choice>
								<xs:element name="content" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:group ref="cur:contentTypeGrp" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
										</xs:complexType>
								</xs:element>
								<xs:element name="long" minOccurs="1" maxOccurs="1" />
								<xs:element name="integer" minOccurs="1" maxOccurs="1" />
								<xs:element name="double" minOccurs="1" maxOccurs="1" />
								<xs:element name="boolean" minOccurs="1" maxOccurs="1" />
								<xs:element name="datetime" minOccurs="1" maxOccurs="1" />
								<xs:element name="string" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:choice>
																<xs:element name="plain" minOccurs="1" maxOccurs="1"/>
																<xs:element name="xml" minOccurs="1" maxOccurs="1"/>
														</xs:choice>
												</xs:sequence>
										</xs:complexType>
								</xs:element>
								<xs:element name="collection" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:element name="item" type="cur:value" minOccurs="1" maxOccurs="1"/>
														<xs:element name="size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
										</xs:complexType>
								</xs:element>
						</xs:choice>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="fields">
				<xs:sequence>
						<xs:element name="field" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
										<xs:sequence>
												<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
												<xs:element name="value" type="cur:value" minOccurs="1" maxOccurs="1"/>
												<xs:element name="required" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										</xs:sequence>
								</xs:complexType>
						</xs:element>
				</xs:sequence>
		</xs:complexType>
		<xs:group name="parentType">
				<xs:sequence>
						<xs:element name="parentTypeNS" type="xs:string" />
						<xs:element name="parentTypeName" type="xs:string" />
				</xs:sequence>
		</xs:group>
		<xs:complexType name="textual">
				<xs:sequence>
						<xs:group ref="cur:parentType" minOccurs="0" maxOccurs="1" />
						<xs:element name="fields" type="cur:fields" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="binary">
				<xs:sequence>
						<xs:element name="mimeType" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="fields" type="cur:fields" minOccurs="0" maxOccurs="1" />
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="contentType">
				<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="type">
								<xs:complexType>
										<xs:sequence>
												<xs:choice>
														<xs:element name="textual" type="cur:textual" />
														<xs:element name="binary" type="cur:binary" />
												</xs:choice>
										</xs:sequence>
								</xs:complexType>
						</xs:element>
						<xs:element name="status" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
										<xs:sequence>
												<xs:element name="value" minOccurs="1" maxOccurs="unbounded" />
										</xs:sequence>
								</xs:complexType>
						</xs:element>
				</xs:sequence>
				<xs:attribute name="namespace" type="xs:string" use="required" />
		</xs:complexType>
		<xs:element name="contentTypes">
				<xs:complexType>
						<xs:sequence>
								<xs:element name="contentType" type="cur:contentType" minOccurs="1" maxOccurs="unbounded" />
						</xs:sequence>
				</xs:complexType>
		</xs:element>
</xs:schema>

=== SmartITEngineering/smart-cms/content-spi-impl/src/test/resources/content-type-def-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-1.xml
    Created on : September 25, 2009, 1:10 PM
    Author     : imyousuf
    Description:
        Test content type definition.
-->
<contentTypes  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.smartitengineering.com/smart-cms/content/content-type-schema'
   xsi:schemaLocation='http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../../../content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd'>
  <contentType namespace="asdfasdf1">
    <name>XYZ</name>
    <fields>
      <field>
        <name>fieldA</name>
        <value>
          <content>
            <typeNS>asdfasdf1</typeNS>
            <typeName>XYZ</typeName>
          </content>
        </value>
      </field>
      <field>
        <name>fieldB</name>
        <value>
          <collection>
            <value>
              <integer />
            </value>
          </collection>
        </value>
      </field>
      <field>
        <name>fieldB</name>
        <value>
          <collection>
            <value>
              <content>
                <typeNS>jpeg</typeNS>
                <typeName>RST</typeName>
              </content>
            </value>
          </collection>
        </value>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>
  <contentType namespace="jpeg">
    <name>RST</name>
    <fields>
      <field>
        <name>image</name>
        <value>
          <other>
            <mimeType>image/jpeg</mimeType>
          </other>
        </value>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>
</contentTypes>
